### ISSUE TITLE
Does this mean Nolvorite is coming out of retirement?

### ISSUE THREAD

**Issue by Operation420** [nolvorite/captiv8#1]
Does this mean [Nolvorite](http://nolvorite.com) is no longer retired from foruming?

See you on [op420](http://operation420.net)!!!

**Comment by psphomebrew** [comment]
Nice

**Comment by Operation420** [comment]
[Nolvorite](http://nolvorite.com) has retired from foruming indefinitely. The launch of this project [does not indicate his return](https://github.com/nolvorite/captiv8/issues/2#issuecomment-92151057).

**Comment by psphomebrew** [comment]
His greatest achievements are over :(
