### ISSUE TITLE
Post on operation420.net

### ISSUE THREAD

**Issue by Operation420** [nolvorite/captiv8#2]
#1

**Comment by Operation420** [comment]
Does this mean [Nolvorite](http://nolvorite.com) is no longer retired from foruming?

See you on [op420](http://operation420.net)!!!

**Comment by nolvorite** [comment]
lol I can't believe you still have that up. And i'm not posting anymore lol, why is this here

**Comment by Operation420** [comment]
What up?

**Comment by Operation420** [comment]
#3
