### ISSUE TITLE
Stop hatin'

### ISSUE THREAD

**Issue by Operation420** [nolvorite/captiv8#3]
@nolvorite  Stop hatin'

**Comment by Operation420** [comment]
You are in direct violation of the [Anti-Hatin' Protocol](http://operation420.net/forum/viewtopic.php?t=268)

**Comment by psphomebrew** [comment]
Hatin' is bad, in an ideal world everyone would get along, but not everyone plays well with others unfortunately :(

**Comment by Operation420** [comment]
**Known fact:** Jealously causes hatin'

**Comment by Operation420** [comment]
Closes #4
